#!/bin/sh
CROSS_COMPILE="/opt/miyoomini-toolchain/bin/arm-linux-gnueabihf-"
CFLAGS="-Ofast -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -march=armv7ve+simd -std=c99 -shared -fPIC -Wall -s"
${CROSS_COMPILE}gcc -o normal3x.so normal3x.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd2x_dark.so lcd2x_dark.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd2x_light.so lcd2x_light.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd3x_stripe.so lcd3x_stripe.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd3x_mosaic.so lcd3x_mosaic.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd3x_dark.so lcd3x_dark.c ${CFLAGS}
${CROSS_COMPILE}gcc -o lcd3x_light.so lcd3x_light.c ${CFLAGS}
${CROSS_COMPILE}gcc -o vertical3x4.so vertical3x4.c ${CFLAGS}
